Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            -
                Label:
                    default: Export VPC Stack Name
                Parameters:
                    - ExportVpcStackName
            -
                Label:
                    default: Database Parameters
                Parameters:
                    - DatabaseInstanceIdentifier
                    - DatabaseName
                    - DatabaseUser
                    - DatabasePassword
                    - DatabaseBackupRetentionPeriod
                    - DatabaseAllocatedStorage
                    - DatabaseInstanceClass
                    - MultiAZDatabase
AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an RDS database with MYSQL 5.7 engine
  # Create RDS
Parameters:
  ExportVpcStackName:
    Description: The name of the vpc stack that exports values
    Type: String
  DatabaseInstanceIdentifier:
    AllowedPattern: '[a-zA-z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with letter and contain alphanumeric character
    Default: mysqldb
    Description: Instance identifier name
    MaxLength: 60
    MinLength: 1
    Type: String

  DatabaseName:
    AllowedPattern: '[a-zA-z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with letter and contain alphanumeric character
    Default: applicationdb
    Description: MySql Database name
    MaxLength: 64
    MinLength: 1
    Type: String

  DatabaseUser:
    AllowedPattern: '[a-zA-z][a-zA-Z0-9]*'
    ConstraintDescription:  Must begin with letter and contain alphanumeric character
    Default: admin
    Description: Username for MySql Database access
    MaxLength: 60
    MinLength: 1
    NoEcho: true
    Type: String

  DatabasePassword:
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription:  Must contain only alphanumeric character
    Default: Gopinath123
    Description: Password for database access
    MaxLength: 41
    MinLength: 8
    NoEcho: true
    Type: String

  DatabaseBackupRetentionPeriod:
    ConstraintDescription: Database backup retention period must be between 0 and 35 days
    Default: 0
    Description:  The number of days for which automatic Db snapshorts are retained
    MaxValue: 35
    MinValue: 0
    Type: Number

  DatabaseAllocatedStorage:
    ConstraintDescription: Must be between 5 and 1024gb
    Default: 20
    Description: The size of database (gb)
    MaxValue: 1024
    MinValue: 5
    Type: Number

  DatabaseInstanceClass:
    AllowedValues:
      - db.t1.micro
      - db.t2.micro
      - db.m1.small
      - db.m1.medium
      - db.m1.large
    ConstraintDescription: Must be select a valid database instance type
    Default: db.t2.micro
    Description: The database instance type
    Type: String

  MultiAZDatabase:
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be either true or false
    Default: false
    Description: Create a multi-AZ mysql rds instance
    Type: String
Resources:
    # DatabaseSubnetGroup:
    #     Type: AWS::RDS::DBSubnetGroup
    #     Properties:
    #         DBSubnetGroupDescription: Subnet group for RDS database
    #         SubnetIds:
    #             - Fn::ImportValue: !Sub ${ExportVpcStackName}-PrivateSubnet0
    #         Tags:
    #             - Key: Name
    #               Value: database subnet

    DatabaseInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            AllocatedStorage: !Ref DatabaseAllocatedStorage
            AvailabilityZone: !Select [ 0, !GetAZs  '' ]
            BackupRetentionPeriod: !Ref DatabaseBackupRetentionPeriod
            DBInstanceClass: !Ref DatabaseInstanceClass
            DBInstanceIdentifier: !Ref DatabaseInstanceIdentifier
            DBName: !Ref DatabaseName
            # DBSubnetGroupName: !Ref DatabaseSubnetGroup
            Engine: MySQL
            EngineVersion: 5.7.31
            MasterUsername: !Ref DatabaseUser
            MasterUserPassword: !Ref DatabasePassword
            MultiAZ: !Ref MultiAZDatabase
            VPCSecurityGroups:
                - Fn::ImportValue: !Sub ${ExportVpcStackName}-DataBaseSecurityGroup